version '2'

services:
 sonarqube:
  image: sonarqube
  ports: 
     - "9000:9000"
  networks:
     - sonarnet
  enviroment:
     - SONARQUBE_JDBC_URL:postgresql://db:5432/sonar
  volumes:
     - sonarqube_conf:/opt/sonarqube/conf
     - sonarqube_data:/opt/sonarqube/data
     - sonarqube_tmp:/opt/sonarqube/temp
     - sonarqube_extensions:/opt/sonarqube/extensions
     - sonarqube_bundled-plugins:/opt/sonarqube/lib/blundled-plugins
  restart: always


 db:
  image : postgres
  networks:
     - sonarnet
  enviroment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
  volumes:
     - postgresql:/var/lib/postgresql
     - postgresql_data:/var/lib/postgresql/data
   restart: always
        
networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:   
  sonarqube_data:  
  sonarqube_tmp:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
